### ISSUE TITLE
Source Code Error

### ISSUE THREAD

**Issue by Crysiv4n** [codingMASTER398/Kahootflood.weebly.com#7]
**Describe the bug**
Hello, my bug is when I want to open the flood.js on the source code says me :

Preparing...
internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module 'readline-sync'
Require stack:
- C:\Users\ialsi\Downloads\Kahootflood.weebly.com-main\flood.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\ialsi\Downloads\Kahootflood.weebly.com-main\flood.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\ialsi\\Downloads\\Kahootflood.weebly.com-main\\flood.js'
  ]
}

**Expected behavior**
I expected that the program or file is going to run correct but no.

**Screenshots**
https://cdn.discordapp.com/attachments/737377106761089165/810549695210455040/Captura_de_pantalla_174.png

**Desktop (please complete the following information):**
 - OS: Win 10 Normal
 - Version: 20H2

PD: I'm Spanish so if you don't understand me tell me in Discord Crys_iv4n#8242

**Comment by codingMASTER398** [comment]
Hey there!
If you are getting this error, it is with the source code.
Make sure you have the "package.json" file, then in the terminal type "npm install"
Hope that helps!
